use_frameworks!

platform :ios, '8.0'

target 'MEFacebookAdapter_Example' do
  pod 'MEFacebookAdapter', :path => '../'

  target 'MEFacebookAdapter_Tests' do
    inherit! :search_paths

    
  end
end
